### ISSUE TITLE
1.12.0.2 does not start on OSX

### ISSUE THREAD

**Issue by mudlee** [tommyettinger/gdx-liftoff#136] opened 2023-10-04 07:02 UTC
I think something is off with these commits:
- [https://github.com/tommyettinger/gdx-liftoff/commit/09a261db14b5520b98116d94b89a0cc568e62693](https://github.com/tommyettinger/gdx-liftoff/commit/09a261db14b5520b98116d94b89a0cc568e62693)
- [https://github.com/tommyettinger/gdx-liftoff/commit/f98c8b2e4199014e59cc581bf47f69a1f46eb5e1](https://github.com/tommyettinger/gdx-liftoff/commit/f98c8b2e4199014e59cc581bf47f69a1f46eb5e1)
- [https://github.com/tommyettinger/gdx-liftoff/commit/ef282013c4824d580d09e7cb1b8c20df033af44d](https://github.com/tommyettinger/gdx-liftoff/commit/ef282013c4824d580d09e7cb1b8c20df033af44d)

Info:
- I use Java 21 zulu
- Previous build works. 
- Let me know if I can help testing.

```bash
java -jar gdx-liftoff-1.12.0.4.jar 
Exception in thread "main" java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
	at org.lwjgl.glfw.EventLoop.check(EventLoop.java:33)
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1078)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:88)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:138)
	at gdx.liftoff.MainKt.main(Main.kt:132)
	at gdx.liftoff.MainKt.main(Main.kt)
```

**Comment by JojoIce** [comment] 2023-10-04 07:51
Indeed, I can confirm the same on my machine. 
If you are really eager to use that build, then you can do as it states and instead start with:
`java -jar -XstartOnFirstThread gdx-liftoff-1.12.0.4.jar`
We have to hope that @tommyettinger gets some nice tool to set up his projects when building liftoff :D

**Comment by tommyettinger** [comment] 2023-10-06 04:04
Ah geez, I just saw this issue now. I'll try to investigate as best I can, and I'll place some beta jars in this issue thread if I think one may help solve this.

**Comment by tommyettinger** [comment] 2023-10-06 04:18
It looks like the first commit you linked might be the culprit -- I got the changed code from Guacamole, and I think it also could be wrong there. As far as I can tell, it's getting a property that should only have a value on Graal Native Image, or `""` if it wasn't found. But then, it checks if that *is* empty, rather than *is not* -- causing it to stop execution if it isn't run on Graal, or keep going if it is on Graal. But it only should stop execution *on* Graal... So anyway, here's a beta JAR. I hope this works at least a little better! Or gets some useful information, at least. 

[gdx-liftoff-1.12.0.5-SNAPSHOT.jar.zip](https://github.com/tommyettinger/gdx-liftoff/files/12826853/gdx-liftoff-1.12.0.5-SNAPSHOT.jar.zip)

**Comment by mudlee** [comment] 2023-10-06 04:42
The snapshot you atteched does work correctly :)

**Comment by tommyettinger** [comment] 2023-10-06 06:34
Great! That means a) I'll push a new fix release soon, and b) I'll go ahead and mention this in an issue on crykn's guacamole repo.

Leaving this open until I do the release.

**Comment by tommyettinger** [comment] 2023-10-18 06:01
Doing the release now. Closing.

**Closed by tommyettinger** 2023-10-18 06:01 UTC
