### ISSUE TITLE
There should be an option for `lombok`

### ISSUE THREAD

**Issue by payne911** [tommyettinger/gdx-liftoff#54] opened 2021-09-19 18:00 UTC
A sample commit: https://github.com/lyze237-gamejams/HamballRacers/commit/e7341fc671978f98797248b53c2e91c6aa0b7895

**Comment by tommyettinger** [comment] 2021-09-23 22:00
I can look into it, but I would need some information on how to add Lombok to all supported platforms (iOS and Android, especially), or to not support Lombok on anything but LWJGL3 and HTML. I'm often frustrated by how the existing dependency code handles less-common dependency configurations, like `annotationProcessor`, but I'm at a loss as to how I would add `lom`...

**Comment by payne911** [comment] 2021-09-24 02:30
I hadn't thought about iOS. Maybe @lyze237 knows?

I doubt it doesn't work for Android, but I indeed haven't tested it. What is libGDX's JDK version limit to target Android, again? In any case, I doubt the generated code isn't valid even for Java 7.

**Comment by lyze237** [comment] 2021-09-24 06:29
Theoretically it shouldn't matter as it's just a preprocessor, but I'll test ios today (if I can figure out how ios + libgdx works). :)

**Comment by JojoIce** [comment] 2021-09-24 09:43
I have been using Lombok for some time on Android, iOS, Desktop and lwjgl3. As I recall you don't need to do anything other than updates to gradle in core. I can check later to make sure. @payne911 I think you should be able to skip the changes in lwjgl3/build.gradle from your commit above and remove the same section from the HTML as well.

So theoretically for Android, iOS, Desktop and lwjgl3 **all** you need is to update core/build.gradle with two lines:
	implementation "org.projectlombok:lombok:1.18.+"
	annotationProcessor "org.projectlombok:lombok:1.18.+"

Better use params for version as payne911 does. HTML seems to need some more work. At least I can say that it works fine for iOS and Android.

**Comment by lyze237** [comment] 2021-09-24 11:10
The lwjgl3 part in there is only if you want lombok to be also present in the lwjgl module.

For html you need everything I changed in the gradle file, else it won't work with superdev reloads.

**Comment by lyze237** [comment] 2021-09-24 11:34
I tested both mobile platforms (on emulators) to get a second confirmation (Since @JojoIce said it works already):
* Confirmed works on iOS (tested core project only).
* Confirmed works on android (tested core project only).

**Comment by JojoIce** [comment] 2021-09-24 12:01
> In the super hamball racers project I added it to lwjgl3 as I wanted lombok to work in the lwjgl3 module.
> It's not in the lombok example project as I didn't want that in that project.

Fair point. Maybe that should be an option, or added as a comment in the documentation. Most people would not need or want that, but clearly some do, but normally you would just want it in core I guess.

**Comment by payne911** [comment] 2021-09-24 13:49
> Better use params for version as payne911 does.

I was pointing to Lyze's work, btw. :)

> I tested both mobile platforms

Will you update your wonderful repo?

> I'm often frustrated by how the existing dependency code handles less-common dependency configurations

It's been a little while since I've brought this up, but too bad no one wants the "enterprise" code. :p

https://github.com/payne911/gdx-setup-generator/blob/a5bbe476f4cf08f7f8112fd99b8a65b251c6254d/src/main/java/com/github/payne/logic/folders/root/BuildGradleFile.java#L18

**Comment by lyze237** [comment] 2021-09-24 14:22
> Will you update your wonderful repo?
Do I need to? Nothing changed really, just both modules added.

**Comment by payne911** [comment] 2021-09-25 02:41
> Do I need to? Nothing changed really, just both modules added.

Maybe just mention how the same showcased commits would work for all of the platforms supported by libGDX (mentioning specifically `Android` and `iOS`) ?

**Comment by tommyettinger** [comment] 2021-10-07 08:20
Has anyone had a chance to test this? I kinda doubt anyone built Liftoff, so here's a snapshot JAR: 
[gdx-liftoff-1.10.0.7-SNAPSHOT.jar.zip](https://github.com/tommyettinger/gdx-liftoff/files/7300293/gdx-liftoff-1.10.0.7-SNAPSHOT.jar.zip) If anyone can verify that this does what they want from Lombok, I can close this issue. @payne911 , you're good at finding tiny issues, want to give this a shot?

**Comment by tommyettinger** [comment] 2021-10-11 09:59
So, I'm thinking I will release a new version once Gradle supports Java 17, which should be in a few weeks (Gradle 7.3 has no RC yet, but the nightly seems to be moving forward). That will include these Lombok changes, plus a few other fixes and improvements that are in the git HEAD now. I think supporting the current LTS Java version should be done ASAP, so as soon as Gradle releases, I'll try to get Liftoff updated right away. If anyone has any further requests for the Lombok support, feel free to comment; I think this can be closed now that Lyze tested and found it suitable.

**Closed by tommyettinger** 2021-10-11 09:59 UTC
