### ISSUE TITLE
Could not find lwjgl-glfw-3.2.3-natives-linux-arm32.jar

### ISSUE THREAD

**Issue by TomBell06** [tommyettinger/gdx-liftoff#49] opened 2021-07-22 14:38 UTC
The error comes up when I create a project with gdx-liftoff

**Comment by Seggan** [comment] 2021-08-13 01:33
Can confirm

**Comment by tommyettinger** [comment] 2021-08-15 00:25
So, I have very little info given here, but from what I can replicate, this looks like Maven Central could have been down at a few different points, making the dependency unavailable for some period of time. I don't see any specific downtime recorded at https://status.maven.org/uptime , but it doesn't show periods when downloading is unavailable, just uploading. I just now removed `lwjgl-glfw-3.2.3-natives-linux-arm32.jar` from my caches, made a new project using the LWJGL3 platform only, built it and ran without issues. That means this is either a local issue with that dependency on your machines, or more likely it is an issue with Maven Central being (temporarily) unable to supply that dependency. Thankfully, once that dependency does download, Gradle should be able to use it until libGDX eventually updates to LWJGL 3.3.0, which is still unreleased.

Because I can make a new project and build it even with the file in question removed from my caches, I don't think this issue is still valid; if it is, it's not anything I can fix in gdx-liftoff because the problem is with Maven Central. I'm closing; you can reopen if you can provide more information and are still encountering this issue.

**Closed by tommyettinger** 2021-08-15 00:25 UTC
