### ISSUE TITLE
Error copying icon

### ISSUE THREAD

**Issue by siauderman** [tommyettinger/gdx-liftoff#52] opened 2021-08-30 04:36 UTC
Hi, I'm getting this error:

Preparing the project...
com.badlogic.gdx.utils.GdxRuntimeException: Error copying source file: icons\libgdx16.png (Internal)
To destination: C:\Users\WilsonFooYuKang\Documents\Bitbucket\migrate\TuxFight\lwjgl3\src\main\resources\libgdx16.png (Absolute)
  at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:718)
  at com.badlogic.gdx.files.FileHandle.copyTo(FileHandle.java:603)
  at com.github.czyzby.setup.data.files.CopiedFile.save(projectFile.kt:106)
  at com.github.czyzby.setup.data.project.Project.saveFiles(project.kt:121)
  at com.github.czyzby.setup.data.project.Project.generate(project.kt:89)
  at com.github.czyzby.setup.views.dialogs.GenerationPrompt$doBeforeShow$1.run(generationPrompt.kt:45)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

I don't dare to move further because it also appears that no AndroidManifest.xml and other Android files are generated.

**Comment by Frosty-J** [comment] 2021-08-30 13:15
Possibly an antivirus issue? That's what was what before. See #37.

I tested writing to a read-only directory, which returned the error `Error writing file`, and deleting `icons/libgdx16.png` from the JAR stopped gdx-liftoff from opening at all. So enthusiastic antivirus software is currently my bet.

**Comment by tommyettinger** [comment] 2021-09-01 06:08
I believe this was resolved on Discord; it seemed like shortening the destination path made the project complete, but it could also be antivirus. (AV may have caused the initial problem, and by the time the shorter path was created, AV had decided that Liftoff was safe, but we can only guess.) I wasn't sure if the problem was fully resolved in the Discord conversation, but I think it was now that no more has been mentioned. I'll close this now, but feel free to reopen if the issue is still happening. If you encounter a different problem, you can always create a new issue.

**Closed by tommyettinger** 2021-09-01 06:08 UTC
